const caption = 'Three data sources, Google Ads performance, Merchant Center feed, and supplier landed cost, feed into a deterministic margin engine that outputs one row per product with contribution margin, breakeven conversion rate, inline bid editing, and an audit log.';
export default function MarginDiagram() { return <div className="diagram" role="img" aria-label={caption}><svg viewBox="0 0 684 106" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" fontFamily="Inter, system-ui, sans-serif">
<rect x="0" y="0" width="150" height="30" rx="4" fill="var(--dg-fill)" stroke="var(--dg-stroke)"/><text x="75" y="19.5" fontSize="11" fill="var(--dg-ink)" textAnchor="middle">Google Ads performance</text>
<rect x="0" y="38" width="150" height="30" rx="4" fill="var(--dg-fill)" stroke="var(--dg-stroke)"/><text x="75" y="57.5" fontSize="11" fill="var(--dg-ink)" textAnchor="middle">Merchant Center feed</text>
<rect x="0" y="76" width="150" height="30" rx="4" fill="var(--dg-fill)" stroke="var(--dg-stroke)"/><text x="75" y="95.5" fontSize="11" fill="var(--dg-ink)" textAnchor="middle">Supplier landed cost</text>
<g stroke="var(--dg-line)" strokeWidth="1.15" fill="none"><path d="M150 15 H182 Q196 15 196 29 V53"/><path d="M150 53 H196"/><path d="M150 91 H182 Q196 91 196 77 V53"/><path d="M196 53 H226"/></g><path d="M226 49 L233 53 L226 57 Z" fill="var(--dg-line)"/>
<rect x="237" y="34" width="150" height="38" rx="4" fill="var(--dg-solid)"/><text x="312" y="49" fontSize="11" fontWeight="600" fill="var(--dg-on-solid)" textAnchor="middle">Deterministic</text><text x="312" y="62" fontSize="11" fontWeight="600" fill="var(--dg-on-solid)" textAnchor="middle">margin engine</text>
<path d="M387 53 H417" stroke="var(--dg-line)" strokeWidth="1.15" fill="none"/><path d="M417 49 L424 53 L417 57 Z" fill="var(--dg-line)"/>
<rect x="428" y="14" width="252" height="78" rx="4" fill="var(--dg-fill)" stroke="var(--dg-stroke)"/><text x="448" y="39" fontSize="12" fontWeight="600" fill="var(--dg-ink)">One row per product</text><text x="448" y="59" fontSize="10.5" fill="var(--dg-muted)">Contribution margin · Breakeven CVR</text><text x="448" y="77" fontSize="10.5" fill="var(--dg-muted)">Inline bid editing · Audit log</text></svg><p className="diagram-caption" aria-hidden="true">{caption}</p></div>; }
